name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /
            rm -rf /var/www/react-chat/
            rm -rf /home/cloned-repo-react-chat/
            cd /var/www
            mkdir react-chat
            cd /home
            mkdir cloned-repo-react-chat
            cd cloned-repo-react-chat
            git clone https://github.com/Andrii-Yukhymenko/react-chat.git
            cd react-chat/
            cp /var/www/react-chat-env/* /var/www/react-chat
            npm install
            npm run build .env.local
            cp -r build/* /var/www/react-chat
